apiVersion: apps/v1
kind: Deployment
metadata:
  name: minisense-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: minisense-api
  template:
    metadata:
      labels:
        app: minisense-api
    spec:
      containers:
        - name: minisense-api
          image: andrewhubs/minisense-api:e19dfc89369215808545aeb2caefd281dbea48e1
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=10.70.101.167;Port=5432;Database=minisense_db;Username=admin;Password=admin123;"