apiVersion: v1
kind: Service
metadata:
  name: minisense-service
  namespace: default
spec:
  type: LoadBalancer
  loadBalancerIP: 10.70.101.5
  selector:
    app: minisense-api
  ports:
    - port: 80
      targetPort: 8080