# This is a generated file. Not intended for manual editing.
services:
  minisense-api:
    build:
      context: "/Volumes/Storage-NVMe/Developer/MiniSense"
      dockerfile: "src/MiniSense.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/MiniSense.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "minisense.api:dev"
    ports: []
    volumes:
    - "/Volumes/Storage-NVMe/Developer/MiniSense/src/MiniSense.API:/app:rw"
    - "/Volumes/Storage-NVMe/Developer/MiniSense:/src:rw"
    - "/Users/andrew/.nuget/packages:/home/app/.nuget/packages"
    working_dir: "/app"
